### ISSUE TITLE
Install earlier version

### ISSUE THREAD

**Issue by bchileen** [FluvialGeomorph/FluvialGeomorph-toolbox#17]
Need to rollback to version pre-feature dataset (November 15thish) to test geopackage implementation

**Comment by mpdougherty** [comment]
@tadarby12 and I configured `COE-MVRWK-56824` with toolbox [v0.1.5](https://github.com/FluvialGeomorph/FluvialGeomorph-toolbox/releases/tag/v0.1.5) (before the file geodatabase feature dataset change) and manually installed `fluvgeo` [v0.1.36](https://github.com/FluvialGeomorph/fluvgeo/releases/tag/0.1.36) (before the file geodatabase feature dataset change). 

1. `02 - Hydro DEM` failed. Error said something like "can't create raster in geopackage".
2. `06 - Flowline Points` fails with the following message:
`06 - Flowline Points
=====================
Parametersoutput_workspace     Z:\Work\FluvialGeomorph\Projects\GEOPackage\WilsonCreek_2019.gpkgflowline     Z:\Work\FluvialGeomorph\Projects\GEOPackage\WilsonCreek_2019.gpkg\main.flowlinedem     Z:\Work\FluvialGeomorph\Projects\GEOPackage\dem_hydrokm_to_mouth     0station_distance     1calibration_points     point_id_field     measure_field     search_radius     25 Metersflowline_points     
=====================
MessagesStart Time: Tuesday, March 7, 2023 2:24:56 PM
Workspace: Z:\Work\FluvialGeomorph\Projects\GEOPackage\WilsonCreek_2019.gpkg
flowline: main
km_to_mouth: 0
DEM: dem_hydro
Station distance: 1
Simplified flowline: flowline_simplify
Densified verticies of flowline: flowline_densify
Converted densfied flowline to a route: flowline_densify_route
Traceback (most recent call last):  File "Z:\Work\FluvialGeomorph\Tools\FluvialGeomorph-toolbox-0.1.5\tools\_06_FlowlinePoints.py", line 203, in <module>    # Call the StreamProfilePoints function with command line parameters  File "Z:\Work\FluvialGeomorph\Tools\FluvialGeomorph-toolbox-0.1.5\tools\_06_FlowlinePoints.py", line 187, in main    out_property = "Z",  File "Z:\Work\FluvialGeomorph\Tools\FluvialGeomorph-toolbox-0.1.5\tools\_06_FlowlinePoints.py", line 138, in StreamProfilePoints    route_id_field = "ReachName",   File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 4560, in FeatureVerticesToPoints    raise e  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 4557, in FeatureVerticesToPoints    retval = convertArcObjectToPythonObject(gp.FeatureVerticesToPoints_management(*gp_fixargs((in_features, out_feature_class, point_location), True)))  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 512, in <lambda>    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Features: Dataset flowline_densify_route does not exist or is not supported
Failed to execute (FeatureVerticesToPoints).
Failed script 06 - Flowline Points...
Failed to execute (FlowlinePoints).
Failed at Tuesday, March 7, 2023 2:25:02 PM (Elapsed Time: 5.81 seconds)`
