### ISSUE TITLE
Tool 04a - Stream Network Point Issue

### ISSUE THREAD

**Issue by fluvialjack** [FluvialGeomorph/FluvialGeomorph-toolbox#22]
Hi there,

Prewarning that I'm not proficient in python or R to any standard so I apologise in advance if this is a simple user error.

Upon attempting to run 04a I am faced with this error: 

Workspace: D:\ENG_Engeny\Unlicensed Drain Standard\Arc_Work\Engeny_Unlicensed_Drains_Guidance\Model_Testing.gdb
Stream Network: streamnetwork1
Flow Accumulation Model: flow_accumulation_d8
Digital Elevation Model: Filled_DEM
Stream network route created
Traceback (most recent call last):
  File "D:\ENG_Engeny\Unlicensed Drain Standard\Arc_Work\Toolbox\FluvialGeomorph-toolbox-master\tools\_04a_StreamNetworkPoints.py", line 164, in <module>
    arcpy.Delete_management(in_data = stream_network_route)    
  File "D:\ENG_Engeny\Unlicensed Drain Standard\Arc_Work\Toolbox\FluvialGeomorph-toolbox-master\tools\_04a_StreamNetworkPoints.py", line 155, in main
    field = arcpy.Describe(dem).baseName, 
  File "D:\ENG_Engeny\Unlicensed Drain Standard\Arc_Work\Toolbox\FluvialGeomorph-toolbox-master\tools\_04a_StreamNetworkPoints.py", line 81, in StreamNetworkPoints
    out_feature_class = stream_network_route, 
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 4930, in FeatureVerticesToPoints
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 4927, in FeatureVerticesToPoints
    retval = convertArcObjectToPythonObject(gp.FeatureVerticesToPoints_management(*gp_fixargs((in_features, out_feature_class, point_location), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 512, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000732: Input Features: Dataset D:\ENG_Engeny\Unlicensed Drain Standard\Arc_Work\Engeny_Unlicensed_Drains_Guidance\Model_Testing.gdb\tester\stream_network_route does not exist or is not supported
Failed to execute (FeatureVerticesToPoints).

Failed script 04a - Stream Network Points...
Failed to execute (StreamNetworkPoints).

Any help would be appreciated.

Cheers,
Jack

**Comment by fluvialjack** [comment]
I have found the issue here. The "Reach Name" attribute is being populated as <NULL>. Assigning a unique value to the reach name seems to fix the problem. Not sure if this will allow the tool to work for ongoing steps but it does allow Tool 4a to return the stream network points.
Cheers,
Jack
